name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  CD:
    name: CD-APP
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{secrets.EAS_EXPO_TOKEN}}
